-- =============================================
-- CREATE REGISTRATION CODES TABLE
-- Stores codes generated by developers for new user registration
-- =============================================

-- Create registration_codes table
CREATE TABLE IF NOT EXISTS registration_codes (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  code VARCHAR(6) NOT NULL UNIQUE,
  created_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  used_at TIMESTAMP WITH TIME ZONE,
  used_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  is_used BOOLEAN DEFAULT FALSE,
  expires_at TIMESTAMP WITH TIME ZONE DEFAULT (NOW() + INTERVAL '30 days')
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_registration_codes_code ON registration_codes(code);
CREATE INDEX IF NOT EXISTS idx_registration_codes_is_used ON registration_codes(is_used);

-- Function to generate and store registration code
CREATE OR REPLACE FUNCTION generate_registration_code(
  p_created_by UUID
)
RETURNS JSON AS $$
DECLARE
  v_code VARCHAR(6);
  v_attempts INT := 0;
  v_max_attempts INT := 10;
BEGIN
  -- Try to generate a unique code
  LOOP
    -- Generate random 6-character alphanumeric code
    v_code := UPPER(SUBSTRING(MD5(RANDOM()::TEXT || CLOCK_TIMESTAMP()::TEXT) FROM 1 FOR 6));
    
    -- Check if code already exists
    IF NOT EXISTS (SELECT 1 FROM registration_codes WHERE code = v_code) THEN
      EXIT; -- Code is unique, exit loop
    END IF;
    
    v_attempts := v_attempts + 1;
    IF v_attempts >= v_max_attempts THEN
      RETURN json_build_object(
        'success', FALSE,
        'message', 'Failed to generate unique code after multiple attempts'
      );
    END IF;
  END LOOP;
  
  -- Store the registration code
  INSERT INTO registration_codes (code, created_by)
  VALUES (v_code, p_created_by);
  
  -- Return success with code
  RETURN json_build_object(
    'success', TRUE,
    'message', 'Registration code generated successfully',
    'code', v_code,
    'expires_in_days', 30
  );
EXCEPTION
  WHEN OTHERS THEN
    RETURN json_build_object(
      'success', FALSE,
      'message', SQLERRM
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to validate registration code
CREATE OR REPLACE FUNCTION validate_registration_code(
  p_code VARCHAR
)
RETURNS JSON AS $$
DECLARE
  v_code_record RECORD;
BEGIN
  -- Find the code
  SELECT * INTO v_code_record
  FROM registration_codes
  WHERE code = UPPER(p_code)
  LIMIT 1;
  
  -- Check if code exists
  IF NOT FOUND THEN
    RETURN json_build_object(
      'success', FALSE,
      'message', 'Invalid registration code'
    );
  END IF;
  
  -- Check if code is already used
  IF v_code_record.is_used THEN
    RETURN json_build_object(
      'success', FALSE,
      'message', 'This code has already been used'
    );
  END IF;
  
  -- Check if code is expired
  IF v_code_record.expires_at < NOW() THEN
    RETURN json_build_object(
      'success', FALSE,
      'message', 'This code has expired'
    );
  END IF;
  
  -- Code is valid
  RETURN json_build_object(
    'success', TRUE,
    'message', 'Code is valid',
    'code_id', v_code_record.id
  );
EXCEPTION
  WHEN OTHERS THEN
    RETURN json_build_object(
      'success', FALSE,
      'message', SQLERRM
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to mark code as used
CREATE OR REPLACE FUNCTION mark_code_as_used(
  p_code VARCHAR,
  p_user_id UUID
)
RETURNS JSON AS $$
BEGIN
  UPDATE registration_codes
  SET is_used = TRUE,
      used_at = NOW(),
      used_by = p_user_id
  WHERE code = UPPER(p_code)
    AND is_used = FALSE;
  
  IF FOUND THEN
    RETURN json_build_object(
      'success', TRUE,
      'message', 'Code marked as used'
    );
  ELSE
    RETURN json_build_object(
      'success', FALSE,
      'message', 'Code not found or already used'
    );
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    RETURN json_build_object(
      'success', FALSE,
      'message', SQLERRM
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant necessary permissions
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON registration_codes TO anon, authenticated;
GRANT EXECUTE ON FUNCTION generate_registration_code TO authenticated;
GRANT EXECUTE ON FUNCTION validate_registration_code TO anon, authenticated;
GRANT EXECUTE ON FUNCTION mark_code_as_used TO anon, authenticated;
